server:
  port: 8081

spring:
    Datasource:
      url: jdbc:mysql://localhost:3306/socialmedia_post
      username: springstudent
      password: springstudent
      driverClassName: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform:
      hibernate:
        ddl-auto: update
    application:
      name: PostService


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
