server:
  port: 8084

spring:
  application:
          name: Security-Service
  Datasource:
    url: jdbc:mysql://localhost:3306/socialmedia_usercredentials
    username: springstudent
    password: springstudent
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform:
    hibernate:
      ddl-auto: update


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
